name: Daily Report Email

on:
  schedule:
    # Runs every day at 8:00 AM IST (which is 2:30 AM UTC)
    - cron: '30 2 * * *'

jobs:
  send_email_report:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python 3.9
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install simple-salesforce pandas requests opencage geopy

    # Step 4: Run the Python script
    - name: Run report script
      run: |
        python site_manager_report.py
