name: Daily Report Workflow

# Schedule the workflow to run daily at 8:00 AM Indian time (UTC+5:30).
on:
  schedule:
    - cron: '00 02 * * *'  # This runs at 2:30 AM UTC, which is 8:00 AM IST.
  workflow_dispatch:  # This allows manual triggering of the workflow.

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository.
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment.
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install dependencies (e.g., simple-salesforce, pandas, requests, etc.).
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install simple-salesforce pandas requests smtplib opencage

      # Step 4: Run your Python script.
      - name: Run Report Script
        env:
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SF_SECURITY_TOKEN: ${{ secrets.SF_SECURITY_TOKEN }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: |
          python send_report_manager.py  # Replace with the actual path to your script
