name: Daily Report Email

on:
  schedule:
    - cron: '30 2 * * *'  # 8:00 AM IST (2:30 AM UTC)
  workflow_dispatch:

jobs:
  send-email-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install simple-salesforce pandas requests opencage  # Removed smtplib

    - name: Verify script presence
      run: |
        ls -al  # Lists files to ensure the Python script is present

    - name: Run Python email script
      env:
        SF_USERNAME: ${{ secrets.SF_USERNAME }}
        SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
        SF_SECURITY_TOKEN: ${{ secrets.SF_SECURITY_TOKEN }}
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      run: |
        python send_report_manager.py || echo "Python script execution failed!"
